env:
  es6: true
  browser: true
extends:
  - "airbnb"
  - "airbnb/hooks"
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  ecmaFeatures: {
    jsx: true
  }
rules:
  max-len: [ "error", 150, {
    ignoreTrailingComments: true,
    ignoreStrings: true,
    ignoreTemplateLiterals: true,
  }]
  react/prefer-stateless-function: off